export const GET_SPORTS = 'GET_SPORTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SPORTS_ERROR = 'SPORTS_ERROR';
export const SPORT_UPDATE_PRICE = 'SPORT_UPDATE_PRICE';
export const SPORT_EVENT = 'SPORT_EVENT';
export const SPORT_SELECTION_EVENT = 'SPORT_SELECTION_EVENT';
export const SPORT_BTN_CLICK = 'SPORT_BTN_CLICK';
